### ISSUE TITLE
Executor azure_openai not found

### ISSUE THREAD

**Issue by vincentgiraud** [microsoft/prompty#64]
With the latest to date standalone Prompty 0.1.13, this previously working code: 

```
path_to_prompty = folder + "/my.prompty"
result = prompty.execute(prompt=path_to_prompty)
```
now fails with the error:
```
ValueError: Executor azure_openai not found
```

If removing the 'type' property from the Prompty file (the [doc](https://pypi.org/project/prompty/) does no longer make it mandatory) I get the following error:
```
KeyError: 'type'
```

**Comment by sethjuarez** [comment]
Two answers here that may help:
1. Extra Installs to make it work
2. `prompty.json` helpers

## Extra Installs
I struggled as I implemented the `serverless` type knowing that eventually there could be multiple types in the future. In order to avoid having to pip install _everything_ for _every type_ when using prompty I decided to move things into sub folders. These subfolders are then imported as needed (based on the type). In order to install what these "subfolder" type's require, you need to install the prompty package (for azure for example) like so:

```bash
pip install prompty[azure]
```

so it will add the appropriate packages. This makes it so we can continue to add prompty types without requiring the installation of unnecessary packages.

## prompty.json
This isn't a well known feature so I though I would say a thing or two about it. If you add a `prompty.json` file to the directory with something like this:

```json
{
  "default": {
    "type": "azure",
    "api_version": "2023-12-01-preview",
    "azure_endpoint": "${env:AZURE_OPENAI_ENDPOINT}",
    "azure_deployment": "${env:AZURE_OPENAI_DEPLOYMENT:gpt-35-turbo}",
    "api_key": "${env:AZURE_OPENAI_KEY}"
  }
}
```
It will use these defaults to fill in _every_ prompty in the same directory with whatever settings you did not set in the file itself. The `type` is always required, however. For Azure OpenAI based prompty's, you can use `azure` or `azure_openai` as the type - both will work because of how the [invoker is registered](https://github.com/microsoft/prompty/blob/main/runtime/prompty/prompty/azure/executor.py#L10-L11).

When prompty's are executed, you can actually pass in an additional `config_name` [property](https://github.com/microsoft/prompty/blob/main/runtime/prompty/prompty/__init__.py#L347) to use other settings to hydrate the prompty execution config (I just changed the property name to avoid confusion - t'will be in the latest build.


Let me know if this helps!!

**Comment by vincentgiraud** [comment]
Thanks, the prompty.json helped we keep an env based config separated from the VSC ones.
